# Generated by Django 2.1.3 on 2019-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
