# Generated by Django 2.1.3 on 2019-03-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0002_transection_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
