# Generated by Django 2.1.3 on 2019-02-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='icon',
            field=models.ImageField(default=1, upload_to='incons/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='icon',
            field=models.ImageField(default=1, upload_to='incons/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
