# Generated by Django 2.1.3 on 2019-02-28 10:41

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20190228_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='icon',
            field=faicon.fields.FAIconField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='icon',
            field=faicon.fields.FAIconField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
